spring:
  application:
    name: oauth2-resource-server

# 该配置无效(官网的配置)
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://127.0.0.1:8079/auth/.well-known/jwks.json

security:
  oauth2:
    resource:
      jwk:
        key-set-uri: http://127.0.0.1:8079/auth/.well-known/jwks.json

server:
  port: 8078
  servlet:
    context-path: /resource